version: '3'
services:
  selenium-hub:
    image: selenium/hub:latest
    environment:
      - SE_OPTS=--disable-telemetry
  chrome:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--disable-telemetry