name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:
  Python-Selenium-Grid-Test:
    runs-on: macos-latest


    steps:
      - name: Initialize Docker File
        run: |
          pwd
          docker --version
          docker-compose -f docker-compose.yml up

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


