name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:

  Python-Selenium-Grid-Test:
    runs-on: ubuntu-latest


    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:latest
        volumes:
          - /dev/shm:/dev/shm
        env:
          HUB_HOST: selenium-hub
          HUB_PORT: 4444
        options: --shm-size="2g"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Files and Directory
        run: ls -lrt

      - name: Initialize Docker File
        run: |
          pwd
          docker ps -a
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#          docker-compose -f docker-compose.yml up

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


