name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:

  Python-Selenium-Grid-Test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Files and Directory
        run: ls -lrt

      - name: Initialize Docker File
        run: |
          pwd
          docker network create grid
          docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub:4.24.0-20240830
          docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub \
              --shm-size="2g" \
              -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
              -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
              selenium/node-chrome:4.24.0-20240830
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#          docker-compose -f docker-compose.yml up

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


