name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:
  Python-Selenium-Grid-Test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Files and Directory
        run: ls -lrt

      - name: Initialize Docker File
        run: |
          pwd
          docker --version
          docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.19.0-20240830
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#          docker-compose -f docker-compose.yml up

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


