name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:
  Python-Selenium-Grid-Test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.0.0
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.0.0
        ports:
          - 5900:5900

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


