name: Selenium-Grid-Test

on:
  workflow_dispatch:

jobs:

  Python-Selenium-Grid-Test:
    runs-on: windows-latest


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Check Files and Directory
        run: dir

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Hub and Node
        run: |
          java -jar selenium-server-4.24.0.jar hub
          java -jar selenium-server-4.24.0.jar node --port 5555
          

#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#          docker-compose -f docker-compose.yml up

      - name: Execute Scripts
        run:
          pytest -s test/TestGrid.py


